twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        address: '%env(ADDRESS)%'
        zip_code: '%env(ZIPCODE)%'
        phone: '%env(PHONE)%'